### ISSUE TITLE
put_d() unexpected remote path handling and issue with absolute Windows paths

### ISSUE THREAD

**Issue by Johnmaras** [byteskeptical/sftpretty#11]
I found two issues with the `put_d()` function.
1. It looks like it doesn't accept absolute Windows paths.
I get the error:
> ValueError: 'C:\\\\Users\\\\johnm\\\\PycharmProjects\\\\project\\\\.other\\\\folder\\\\file' does not start with '\\\\'

2. When I call `put_d("local_folder", "folder")`, I get the following error:
> File "C:\Users\johnm\PycharmProjects\project\venv\lib\site-packages\sftpretty\\\_\_init\_\_.py", line 563, in put
>     confirm=confirm, preserve_mtime=preserve_mtime)
>   File "C:\Users\johnm\PycharmProjects\project\venv\lib\site-packages\sftpretty\\_\_init\_\_.py", line 554, in _put
>     confirm=confirm)
>   File "C:\Users\johnm\PycharmProjects\project\venv\lib\site-packages\paramiko\sftp_client.py", line 759, in put
>     return self.putfo(fl, remotepath, file_size, callback, confirm)
>   File "C:\Users\johnm\PycharmProjects\project\venv\lib\site-packages\paramiko\sftp_client.py", line 714, in putfo
>     with self.file(remotepath, "wb") as fr:
>   File "C:\Users\johnm\PycharmProjects\project\venv\lib\site-packages\paramiko\sftp_client.py", line 372, in open
>     t, msg = self._request(CMD_OPEN, filename, imode, attrblock)
>   File "C:\Users\johnm\PycharmProjects\project\venv\lib\site-packages\paramiko\sftp_client.py", line 822, in _request
>     return self._read_response(num)
>   File "C:\Users\johnm\PycharmProjects\project\venv\lib\site-packages\paramiko\sftp_client.py", line 874, in _read_response
>     self._convert_status(msg)
>   File "C:\Users\johnm\PycharmProjects\project\venv\lib\site-packages\paramiko\sftp_client.py", line 903, in _convert_status
>     raise IOError(errno.ENOENT, text)
> FileNotFoundError: [Errno 2] Path not found.

As I understand, the path it refers to is the remote path. When I debug it, in `put_d()`, the paths it creates are the following:
![image](https://user-images.githubusercontent.com/12174150/189113640-345cd587-51fa-45ee-9744-dd315fcec13a.png)
As you can see, the remotedir "folder/local_folder/file" is probably the issue. In my remote location, it creates the folder "folder". This of course makes sense as it successfully calls `self.mkdir_p(remotedir)` in line 599. Do you think this has to do with the location of the `self.mkdir_p(remotedir)` call? Should there be code that also creates the subfolders of the "local_folder" in the remote location(here the "folder/local_folder" subfolder)?

Thank you for your time.

**Comment by byteskeptical** [comment]
The first issue is definitely a bug that will require some additional logic prior to deal with both absolute types (windows & unix) in a semi-intelligent manner. As for the second, the intent of the put_d function is to limit the content uploaded to a single directory level, which I'm sure you grasp just fine. The call to mkdir_p is an attempt to provide the user with the freedom of choice as to whether they want just the content or the whole structure copied by being explicit in the remotedir parameter. In your example if you want the "local_folder" sub-folder created as well you should pass the remotedir parameter as "folder/local_dir" which should give you the desired result. Please let me know if this is not the case in your testing. Also, any suggestions on making the description more concise for others in this respect would be greatly appreciated.

**Comment by Johnmaras** [comment]
I see your point. As I understand, for the `put_d()` to run successfully, one must run something like `put_d("local_folder", "")` while having already created the folder "local_folder" in the remote path. I tested it and runs correctly. So, as per the above `put_d` example, my local folder's ("local_folder") contents will be copied to the remote folder "/local_folder".

Also, what is the purpose of `put_r()`? I tried calling `put_r("local_folder", "")` but I get the "Path not found" error. For the purpose of testing `put_r()`, I added a sub-folder ("test_folder") under my "local_folder". I tried creating the remote path ("/local_folder/test_folder") following the aforementioned logic, but no luck. I also tried it without manually creating the remote paths first, but still nothing. How should I invoke `put_r()`?

**Comment by byteskeptical** [comment]
Yes, kind of but you shouldn't have to create it first if the initial call is something like `put_d("local_folder", "folder/local_folder")`. If that is not working then there is additional work to be done on that front.

As for `put_r` it can technically be used to achieve the same result but it will recursively upload all sub-folders and their content(s) if they exist. If there are no sub-folders as in your original call to `put_d` then they behave largely the same. At minimum the remotedir parameter for both `put_d` and `put_r` has to be `"."` and should never be empty. Otherwise we are making assumptions about expected behavior that may not be consistent in all use cases.  This however is not the case for the `put` call which will technically allow you to not pass a remotedir parameter by making the assumption that you want to maintain  the localfile's name and simply upload it to the remote root directory.

**Comment by byteskeptical** [comment]
Could you post the full trace for the first issue like you did for the second please, I'm having some issues reproducing the behavior.

**Comment by Johnmaras** [comment]
Sorry for the late reply.

Here is the traceback:
Traceback (most recent call last):
  File "C:/Users/johnm/PycharmProjects/test_sftp/main.py", line 12, in <module>
    con.put_d("C:\\\\Users\\\\johnm\\\\PycharmProjects\\\\test_sftp\\\\test_dir", ".")
  File "C:\Users\johnm\PycharmProjects\test_sftp\venv\lib\site-packages\sftpretty\\\_\_init\_\_.py", line 608, in put_d
    for localpath in Path(localdir).iterdir()
  File "C:\Users\johnm\PycharmProjects\test_sftp\venv\lib\site-packages\sftpretty\\_\_init__.py", line 609, in <listcomp>
    if localpath.is_file()
  File "C:\Users\johnm\AppData\Local\Programs\Python\Python37\lib\pathlib.py", line 900, in relative_to
    .format(str(self), str(formatted)))
ValueError: 'C:\\\\Users\\\\johnm\\\\PycharmProjects\\\\test_sftp\\\\test_dir\\\\file.txt' does not start with '\\\\'

I tried calling:
1. put_d("C:\\\\Users\\\\johnm\\\\PycharmProjects\\\\test_sftp\\\\test_dir", "test_dir")
2. con.put_d("C:\\\\Users\\\\johnm\\\\PycharmProjects\\\\test_sftp\\\\test_dir", ".")

Both cases yield the same error. In case of number 1 the "test_dir" gets created, if that's of any help.

**Comment by byteskeptical** [comment]
Can you confirm if the linked pull request solves the issue?

**Comment by Johnmaras** [comment]
Same error.

```
Traceback (most recent call last):
  File "C:/Users/johnm/PycharmProjects/sftpretty_original/.other/file.py", line 17, in <module>
    sftp_con.put_d("C:\\Users\\johnm\\PycharmProjects\\sftpretty_original\\.other\\test_sftp\\test_dir", "test_dir")
  File "C:\Users\johnm\PycharmProjects\sftpretty_original\sftpretty\__init__.py", line 619, in put_d
    for localpath in Path(localdir).iterdir()
  File "C:\Users\johnm\PycharmProjects\sftpretty_original\sftpretty\__init__.py", line 620, in <listcomp>
    if localpath.is_file()
  File "C:\Program Files\Python37\lib\pathlib.py", line 900, in relative_to
    .format(str(self), str(formatted)))
ValueError: 'C:\\Users\\johnm\\PycharmProjects\\sftpretty_original\\.other\\test_sftp\\test_dir\\file1.txt' does not start with '\\'
```

Folder structure:
```
test_sftp
    |   file2.txt
    |
    \---test_dir
            file1.txt
```

**Comment by byteskeptical** [comment]
Can you verify your pathlib module version `pip3 show pathlib`? Or can you try on a version of Python >= 3.8. I'm starting to think this may be related to https://bugs.python.org/issue19918.

**Comment by byteskeptical** [comment]
I'll leave this open for another week to give you some additional time. I understand other things maybe taking your time so if you find this to not be the aforementioned bug we can re-open this issue. Thanks for the feedback!
