### ISSUE TITLE
Need less logging 

### ISSUE THREAD

**Issue by grogu1971** [byteskeptical/sftpretty#17]
Question how can I turn down the amount of logging that sftpretty does on info?

**Comment by byteskeptical** [comment]
There is no easy way at the moment. You can access the underlying log variable and pass a basicConfig() but that is neither ideal or convenient. I'll work on a PR for this.

**Comment by byteskeptical** [comment]
This feature is ready. You can now pass `log_level='error'` through `CnOpts()`which should be pretty quiet. Example provided in the README. If you get a chance any feedback is appreciated

**Comment by trypod33** [comment]
Thanks we will update and test in the next couple of weeks

**Comment by grogu1971** [comment]
Thank you
