### ISSUE TITLE
AttributeError: str object has no attribute root for put_d in localdir.root 

### ISSUE THREAD

**Issue by mawaliya** [byteskeptical/sftpretty#21]
in `put_d` method, when we pass the localdir arg a string, it will give this error:
 
```
  File "/home/smuslim/repos/qa-all-python-tests/.venv/lib/python3.10/site-packages/sftpretty/__init__.py", line 860, in <listcomp>
    .joinpath(localpath.relative_to(localdir.root).as_posix())
AttributeError: 'str' object has no attribute 'root'
```

For Linux, I don't see anywhere localdir as a Path instance but in this line of code it's calling the Path method.

Expected: put_d works when the localdir arguments is a valid localpath string.

**Comment by byteskeptical** [comment]
Thanks for catching this. You're expectation should produce results now.
