### ISSUE TITLE
Question: Is the put_d method expected to upload files to remote path with the same path as localpath?

### ISSUE THREAD

**Issue by mawaliya** [byteskeptical/sftpretty#24]
Question:
Is the put_d method expected to upload files to remote path relative to localpath's path?

Example I have two files 
file1.txt and file2.txt 
in my local path `/home/mawaliya/test/` 
that I want to upload to 
a remote sftp folder `inbox`

When I call `put_d("/home/mawaliya/test", "inbox")`
Remote paths for each file will be relative to local directory. 
For example:
`inbox/home/mawaliya/test/file1.txt`

 I do not have these directories set up remotely, so it  throws IOError - FileNotFoundError.

Is it expected ?
I am expecting my remote path for the files to be:
`inbox/file1.txt`
`inbox/file2.txt`

**Comment by byteskeptical** [comment]
It's not relative but the recursive functions whether `put_d()` or `put_r()` will maintain the directory structure of the `localdir` parameter and its contents. Your expectations are not quite right but it should not include the parent portion of the localdir path in the remote. To be clear of the expectations using your example:

### put_d remotepath
`inbox/test/file1.txt`
`inbox/test/file2.txt`

The PR I've attached should fix this. Can you confirm when you get a chance?

**Comment by mawaliya** [comment]
Thank you for the prompt fixed and the clarification. I have checked it just now, got an issue in creating the remote path directories. In terms of expected result, I was expecting a more predicted and naive way which is, in my opinion whatever files in a `locadir`, will be in `remotedir` , ignoring the parents or the stem. So no hidden functionalities that it will create a stem folder in remote. Then when stem and parent become important, `put_r` will do the job. But I can still work with this approach by naming my localdir to be the same name with the remotedir.

**Comment by mawaliya** [comment]
@byteskeptical (wave)
