### ISSUE TITLE
Put_d has issue in creating remote directory

### ISSUE THREAD

**Issue by mawaliya** [byteskeptical/sftpretty#27]
During creating of remote directory the code will complain because `localdir` is not a Path instance yet.

[` self.mkdir_p(Path(remotedir).joinpath(localdir.stem).as_posix())`](https://github.com/byteskeptical/sftpretty/blob/ca413cdf0ff0db5242dc325c7bc5b9455bb33c1e/sftpretty/__init__.py#L651)

Expected:
The line above is called after we have localdir as a Path instance.

**Comment by byteskeptical** [comment]
I've noticed, I actually have a PR in the works already.
