### ISSUE TITLE
Doesn't use SSH config file.

### ISSUE THREAD

**Issue by Magicrafter13** [byteskeptical/sftpretty#37]
I think this is technically a feature request, not a bug, but:

I got the library working fine as a replacement for pysftp, which is good, but there's one thing about pysftp that bothered me and it's still here: it doesn't read the user's ~/.ssh/config file (or seem to have a function you can call to read it).

I shouldn't have to force my program (using the library) to get the host IP address (if using a custom name, such as "home"), username, and keyfile to use with the server, when the user may very well already have all that information stored inside their config file.

Even if it doesn't read it by default, the option should be there to read it via some function.

**Comment by byteskeptical** [comment]
I completely agree and has been something that has bothered me for a while as well. There are however some compatibility issues across the OS's (Windows specifically). I'll look into providing the use of config as an option but it almost certainly won't be enabled by default.

**Comment by Magicrafter13** [comment]
I can't speak for all versions of Windows, but up to date versions of Windows 10, and 11, have OpenSSH built in, and the applications included in that suite will read from `~/.ssh/config` if it is available (`%USERPROFILE%\.ssh\config`).

I'm no Python expert, but I believe something in `import os` will expand ~ to the user's home directory on both OS types.

**Comment by byteskeptical** [comment]
That is true but in my admittedly limited experience the linux sub-system is a completely seperate file-system and `~` doesn't default to the linux home location. I'm also not sure if the sub-system is enabled by default on all versions of 10 or 11 or if it is a toggle-able feature on some/all.

**Comment by byteskeptical** [comment]
Just need to add some tests before merging.

**Comment by byteskeptical** [comment]
The feature is ready and enabled by default. I've updated the documentation with the nitty gritty but just going to iterate some important notes. By default the current procedure checks a user's default home location `~/.ssh/config` but will not fail if it doesn't exist and simply sets a minimal config with no options. Trying to keep backwards compatibility in mind (those words make me cringe) I've tried to make the feature as transparent as possible when not being used while doing my best to mimic the traditional seemless config experience if you do. Currently config options take precedent over parameters but all this behavior is subject to change based on community feedback. Currently the biggest issue I forsee is the growing delta between supported security option algorithms in paramiko and a users SSH program (OpenSSH more than likely). Especially if a config is picked up without the user realizing it is being read.

**Comment by Magicrafter13** [comment]
Just tried out the new release, seems to work perfectly :ok_hand:

The only comment I have, is on your example in the README. You'll likely need to change `config='~/.ssh/config'` to `config=os.path.expanduser('~/.ssh/config')`, otherwise you'll get something like this:

```
Traceback (most recent call last):
  File "/home/matthew/Documents/projects/vidup/main.py", line 20, in <module>
    class Manager(QObject):
  File "/home/matthew/Documents/projects/vidup/main.py", line 217, in Manager
    cnopts = CnOpts(config='~/.ssh/config')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matthew/Documents/projects/vidup/venv/lib/python3.11/site-packages/sftpretty/__init__.py", line 85, in __init__
    self.ssh_config = self.ssh_config.from_path(config)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matthew/Documents/projects/vidup/venv/lib/python3.11/site-packages/paramiko/config.py", line 109, in from_path
    with open(path) as flo:
         ^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '~/.ssh/config'
```

Now I just gotta find a clean way to stop transfers mid-upload(/download), but that's probably an issue for paramiko itself...

**Comment by byteskeptical** [comment]
Wow for shame, an issue of recursion depth, been coding too much javascript lately it seems, tried to save a line and introduced this bug instead. I'm not sure if you mean resuming an download/upload when you say 'stop transfers' but I have PR #39 in the works with that feature.

**Comment by Magicrafter13** [comment]
> Wow for shame, an issue of recursion depth, been coding too much javascript lately it seems, tried to save a line and introduced this bug instead. I'm not sure if you mean resuming an download/upload when you say 'stop transfers' but I have PR #39 in the works with that feature.

Not quite looking for resume. I'm using this library for a program that is used to upload large files (usually ~11 GB) to a Linux server, which is very slow - especially if someone made a mistake or changed their mind :grin: - my current solution is a hacking implementation of `threading.Thread` that I can raise an exception in, and I run sftpretty in that cursed thread haha.

So I mean, my system works, but surely I can't be the only one who might want to, essentially, press Ctrl+C on that SFTP upload/download.
