### ISSUE TITLE
Feature Request: able to set max workers for any ThreadPoolExecutor

### ISSUE THREAD

**Issue by mawaliya** [byteskeptical/sftpretty#41]
Problem: in some cases max number workers can be more than the allowed concurrent connection on sftp server. For example in `get_d`, this will cause EOFError because the server closing the connection.

**Comment by byteskeptical** [comment]
I see. That is very frustrating. I can work on an attribute to the relavant functions to allow setting max workers. In the meantime you can leverage the retry decorator to at least recover in an automated fashion if that makes sense for your use case. This should be more intelligently handled by the SFTP servers and administrators. If the threads are available why can't I use them and finish faster.
