### ISSUE TITLE
paramiko.ssh_exception.SSHException: No hostkey for host [] found.

### ISSUE THREAD

**Issue by etscript** [byteskeptical/sftpretty#48]
When i use 

with Connection('hostname', username='me', password='secret') as sftp:

raise error :

sftpretty.exceptions.HostKeysException: No host keys found!
or
paramiko.ssh_exception.SSHException: No hostkey for host [xxx.xxx.xxx.xxx] found.

**Comment by byteskeptical** [comment]
The error you are running into is what occurs if you don't have a default known_hosts location (Windows?) and don't disable the default hostkey checking by passing or setting CnOpts() prior too making your Connection object as shown below. Can you confirm this resolves your error? You can either create the default location of `~/home/.ssh/known_hosts` in WSL or pass a custom location if desired as an alternative.

``` python3
import CnOpts, Connection from sftpretty

cnopts = CnOpts(knownhosts=None)
cnopts.hostkeys = None
with Connection('host', username='me', password='pass', cnopts=cnopts):
```

**Comment by etscript** [comment]
Perfect! Thank you so much.
That’s exactly what I needed.
