### ISSUE TITLE
pysftp walktree method missing for drop in replacement

### ISSUE THREAD

**Issue by hulleyrob** [byteskeptical/sftpretty#49]
Was this for performance reasons and wont be getting added in the future?

Only asking as im currently converting a script that used it after updating a Catalina based Mac that finally broke and wont connect anymore. Sftpretty is working on the machine but need to covert the rest of the code over.

**Comment by hulleyrob** [comment]
actually looking at the code not even sure what that was being used for have replaced with listdir and replaced get_d with get_r and it all seems to work. Its more that someone might be looking for an exact drop in replacement so not expecting it to be added.

**Comment by byteskeptical** [comment]
That's fair and that verbage is probably overdue for an update. Walktree performance didn't scale well at larger directory sizes and manipulating the resulting object could be another expensive operation. Without prior directory knowledge one could easily end up with duplicate entries requiring additional sanitization step(s). Lastly, using a single list object once ThreadPool was introduced wasn't a good fit in general. Let me know if you run any into additional cases in your switch and thanks for using the library!
