### ISSUE TITLE
Typo in argument name - tires/tries

### ISSUE THREAD

**Issue by Johnmaras** [byteskeptical/sftpretty#9]
Hi,

In [sftpretty/__init__.py:716](https://github.com/byteskeptical/sftpretty/blob/root/sftpretty/__init__.py#L716) there is a typo in the `tries` argument which causes the call to `putfo()` to raise an exception 

> retry() got an unexpected keyword argument 'tires'

**Comment by byteskeptical** [comment]
It's a wheel shame I missed this. Been meaning to compensate for the lack of non-local upload testing in the current suite. This also underscores some additional holes in the current tests the need to be filled. I will dedicate a PR to this in the near future. Thanks for finding this!

**Comment by Johnmaras** [comment]
Happy to help!
